FROM alpine:3.8

# hadolint ignore=DL3018
RUN apk update && apk --update --no-cache add \
    ruby ruby-rake ruby-io-console ruby-json ruby-bundler \
    libstdc++ build-base ruby-dev \
    &&  echo 'gem: --no-document' > /etc/gemrc

RUN gem install bundler --no-ri --no-rdoc

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
