Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "tag_reddit-database" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "reddit-database"
    db.vm.network :private_network, ip: "10.10.10.10"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "db" => ["tag_reddit-database"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "reddit-app" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "reddit-app"
    app.vm.network :private_network, ip: "10.10.10.20"

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
      "app" => ["reddit-app"],
      "app:vars" => { "db_host" => "10.10.10.10"}
      }
      ansible.extra_vars = {
        "deploy_user" => "vagrant",
        "nginx_sites" => { "default" => [
        "listen 80",
        "server_name 'reddit'",
        "location / { proxy_pass http://127.0.0.1:9292;}"]}
      }
    end
  end
end
